"""Prepare local occurrence candidates; keep uncertain CRS and taxonomy explicit.

Input is the original-record ledger generated by the local bird-source audit.
This script does not create gate labels, absence records, or final data splits.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import pandas as pd


def sha256(path: Path) -> str:
    result = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            result.update(block)
    return result.hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, required=True)
    parser.add_argument("--scope", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--source-crs", choices=["EPSG:4326"])
    parser.add_argument("--crs-evidence", help="Required source confirmation if --source-crs is supplied")
    args = parser.parse_args()
    if args.out.exists():
        raise FileExistsError(args.out)
    if args.source_crs and not args.crs_evidence:
        raise ValueError("Confirmed source CRS requires an evidence statement")
    policy = json.loads(args.scope.read_text(encoding="utf-8"))
    columns = [
        "record_id", "source_file", "source_sheet", "source_row", "species_cn",
        "species_latin", "order", "family", "species_code_raw", "site_raw",
        "county_raw", "date_start_raw", "date_end_raw", "date_start_parsed",
        "date_end_parsed", "date_status", "year_parsed", "season_calendar",
        "longitude_raw", "latitude_raw", "longitude_numeric_unconfirmed_crs",
        "latitude_numeric_unconfirmed_crs", "coordinate_status", "crs_status",
        "abundance_raw", "abundance_numeric", "survey_duration_minutes_from_times",
        "duration_status", "survey_event_key_unconfirmed", "model_label_status",
    ]
    data = pd.read_csv(args.ledger, usecols=columns, low_memory=False)
    if data.record_id.isna().any() or data.record_id.duplicated().any():
        raise ValueError("Original-record IDs must be present and unique")
    data["family_normalized"] = data.family.fillna("").astype(str).str.strip()
    data["family_scope"] = "outside_core_family_scope"
    data.loc[data.family_normalized.eq(""), "family_scope"] = "unknown_family"
    data.loc[data.family_normalized.isin(policy["associated_families_separate_from_core"]), "family_scope"] = "associated_wetland_family"
    selected = data.family_normalized.isin(policy["families"])
    data.loc[selected, "family_scope"] = "core_waterbird_family_candidate"
    data["family_latin_scope"] = data.family_normalized.map(policy["families"])
    dates = pd.to_datetime(data.date_start_parsed, errors="coerce")
    data["season_year"] = dates.dt.year + ((dates.dt.month == 12) & (data.season_calendar == "winter")).astype(int)
    data["taxonomy_status"] = "source_names_preserved_pending_synonym_review"
    data["eligible_for_gate_training"] = False
    data["confirmed_source_crs"] = args.source_crs or "UNCONFIRMED"
    data["source_crs_evidence"] = args.crs_evidence or "UNCONFIRMED"
    data["blockers"] = "taxonomy_and_observation_qa_pending;independent_targets_undefined;fold_provenance_missing"
    if not args.source_crs:
        data["blockers"] = "source_crs_unconfirmed;" + data["blockers"]
    core = data.loc[selected].copy()
    counts = pd.to_numeric(core.abundance_numeric, errors="coerce")
    lon = pd.to_numeric(core.longitude_numeric_unconfirmed_crs, errors="coerce")
    lat = pd.to_numeric(core.latitude_numeric_unconfirmed_crs, errors="coerce")
    coordinate_numeric = lon.between(-180, 180) & lat.between(-90, 90)
    positive = counts.gt(0)
    parsed = pd.to_datetime(core.date_start_parsed, errors="coerce").notna()
    core["positive_occurrence_candidate"] = positive & parsed & coordinate_numeric
    occurrences = core.loc[core.positive_occurrence_candidate].copy()
    # This flag exposes potential duplicates; it does not discard legitimate visits.
    unit = ["species_latin", "date_start_parsed", "date_end_parsed", "site_raw",
            "longitude_numeric_unconfirmed_crs", "latitude_numeric_unconfirmed_crs", "abundance_numeric"]
    occurrences["possible_exact_observation_duplicate"] = occurrences.duplicated(unit, keep=False)
    groups = data.groupby(["species_cn", "species_latin", "family_normalized", "family_scope"], dropna=False)
    registry = groups.size().rename("records").reset_index()
    registry["review_status"] = "pending_species_and_synonym_review"
    args.out.mkdir(parents=True)
    core.to_csv(args.out / "waterbird_source_records.csv", index=False, encoding="utf-8-sig")
    occurrences.to_csv(args.out / "waterbird_occurrences_candidate.csv", index=False, encoding="utf-8-sig")
    registry.to_csv(args.out / "species_scope_review.csv", index=False, encoding="utf-8-sig")
    manifest = {
        "status": "CANDIDATE_DATA_ONLY_NOT_READY_FOR_TRAINING",
        "input_ledger_sha256": sha256(args.ledger), "scope_sha256": sha256(args.scope),
        "scope_source_urls": policy["source_urls"], "original_rows": len(data),
        "core_family_records": len(core), "positive_occurrence_candidates": len(occurrences),
        "nonpositive_or_missing_abundance_core_records": int((~positive).sum()),
        "species_cn_distinct": int(core.species_cn.nunique()),
        "species_latin_distinct": int(core.species_latin.nunique()),
        "calendar_season_records": {str(k): int(v) for k, v in core.season_calendar.value_counts().items()},
        "calendar_year_records": {str(k): int(v) for k, v in core.year_parsed.value_counts().sort_index().items()},
        "family_scope_rows": {str(k): int(v) for k, v in data.family_scope.value_counts().items()},
        "possible_duplicate_occurrence_rows": int(occurrences.possible_exact_observation_duplicate.sum()),
        "coordinate_reference_confirmed": bool(args.source_crs),
        "confirmed_source_crs": args.source_crs,
        "source_crs_evidence": args.crs_evidence,
        "independent_gate_targets_available": False,
        "final_split_assigned": False,
        "records_removed_from_original": 0,
        "outputs": {},
    }
    for path in args.out.glob("*.csv"):
        manifest["outputs"][path.name] = {"sha256": sha256(path), "bytes": path.stat().st_size}
    (args.out / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({key: manifest[key] for key in ("status", "original_rows", "core_family_records", "positive_occurrence_candidates", "species_cn_distinct", "species_latin_distinct")}, ensure_ascii=False))


if __name__ == "__main__":
    main()
